; Simple Bootloader
; This bootloader will print "Hello, World!" on the screen
; This was generated by chatgpt o1 as a sample


[BITS 16]       ; We are in 16-bit real mode
[ORG 0x7C00]    ; Origin, where BIOS loads the bootloader

start:
    ; Clear the screen
    xor ax, ax          ; Set AX to 0
    mov ah, 0x00        ; BIOS function: Set video mode
    mov al, 0x03        ; 80x25 text mode
    int 0x10            ; BIOS interrupt

    ; Set cursor position to top-left corner
    mov dh, 0x00        ; Row = 0
    mov dl, 0x00        ; Column = 0
    mov bh, 0x00        ; Page number
    mov ah, 0x02        ; BIOS function: Set cursor position
    int 0x10            ; BIOS interrupt

    ; Print the message
    mov si, msg         ; SI points to the message string

print_char:
    lodsb               ; Load byte at DS:SI into AL, increment SI
    cmp al, 0           ; Check for null terminator
    je hang             ; If zero, end of string
    mov ah, 0x0E        ; BIOS function: Teletype output
    mov bh, 0x00        ; Page number
    mov bl, 0x07        ; Text attribute (white on black)
    int 0x10            ; BIOS interrupt
    jmp print_char      ; Repeat for next character

hang:
    cli                 ; Clear interrupts
    hlt                 ; Halt CPU
    jmp hang            ; Infinite loop

msg db 'Hello, World!', 0

times 510 - ($ - $$) db 0   ; Pad the rest of the boot sector with zeros
dw 0xAA55                   ; Boot signature (must be at offset 510-511)
